apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /home/pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath

---

apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
  labels:
    role: pvc-pod
spec:
  containers:
    - name: pvc-pod
      image: busybox
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: logs-pvc
          mountPath: /data
      command:
        - /bin/sh
        - -c
        - 'while true; do date >> /data/log.txt; sleep 5; done'
  restartPolicy: Never
  volumes:
    - name: logs-pvc
      persistentVolumeClaim:
        claimName: app-pvc
