apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /home/pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-5-4
  labels:
    app: task-5-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-5-4
  template:
    metadata:
      name: task-5-4
      labels:
        app: task-5-4
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: logs-pvc
              mountPath: /usr/share/nginx/html
          ports:
            - containerPort: 80
              protocol: TCP
        - name: worker
          image: busybox
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: logs-pvc
              mountPath: /data
          command:
            - /bin/sh
            - -c
            - 'while true; do date >> /data/index.html; sleep 5; done'
      restartPolicy: Always
      volumes:
        - name: logs-pvc
          persistentVolumeClaim:
            claimName: app-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: task5-4-svc
  labels:
    app: task-5-4
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: task-5-4

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
spec:
  ingressClassName: nginx
  rules:
    - host: demo.localtest.me
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: task5-4-svc
                port:
                  number: 8080